  platform :ios, '10.3'
  use_frameworks!

  # Pods for Fun App
  

  target 'Fun App' do
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireObjectMapper', '~> 5.0'
  end

  target 'Fun AppTests' do
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireObjectMapper', '~> 5.0'
  end

